# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm test --passWithNoTests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Archive production artifacts
        run: mkdir -p ~/artifacts && cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-build
          path: ~/artifacts
